# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 976d24e77652eb7bb6a8046c4eed3b2df47149894ff7b11e4dbdbb55d72b634eb3889b1395b9d5acd2c9e9fcb18d44cfed9cf0ac99e48a97221610c73ad61383

test:
  secret_key_base: d71975b7f51638f5eea8d5abca69d741ce5a86a9e7ec69e0b2b19c9c4e3ea9e44b9db8b72680940f964842911d5b57ecbaddad2e4f9c36d38faa8cfe4b2be549

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
